import express from "express";
import { verifyAuthToken } from "../middleware/verifyAuthToken";
import { getFriends, searchUsers, getUserByUsername, addFriend, scoreMatch } from "../database";
import { toPublicUser } from "../types";

const router = express.Router();

router.get("/friends", verifyAuthToken, async (req, res) => {
    const friends = await getFriends(res.locals.user);
    res.json(friends);
});

// People search — NPCs generated by the world layer show up here too, so there
// are always singers to find and add.
router.get("/users", verifyAuthToken, async (req, res) => {
    const query = typeof req.query.q === "string" ? req.query.q : "";
    if (query === "") {
        res.json([]);
        return;
    }
    const users = await searchUsers(query, res.locals.user);
    res.json(users);
});

// Taste compatibility between any two singers, using the same scoring as the
// Match tab (§5). Both usernames may be written with or without a leading "@".
// The score is symmetric, so a/b order does not matter.
router.get("/match", verifyAuthToken, async (req, res) => {
    const a = typeof req.query.a === "string" ? req.query.a.trim() : "";
    const b = typeof req.query.b === "string" ? req.query.b.trim() : "";
    if (a === "" || b === "") {
        res.status(400).json({ error: "a and b are required usernames" });
        return;
    }

    const userA = await getUserByUsername(a.replace(/^@/, ""));
    if (!userA) {
        res.status(404).json({ error: "Unknown username: " + a });
        return;
    }
    const userB = await getUserByUsername(b.replace(/^@/, ""));
    if (!userB) {
        res.status(404).json({ error: "Unknown username: " + b });
        return;
    }

    const score = await scoreMatch(userA, userB);
    res.json({
        a: toPublicUser(userA),
        b: toPublicUser(userB),
        matchPct: score.matchPct,
        commonSongs: score.commonSongs
    });
});

router.post("/friends", verifyAuthToken, async (req, res) => {
    const user = res.locals.user;
    const username: string = req.body.username;
    if (!username) {
        res.status(400).json({ error: "username is required" });
        return;
    }
    const other = await getUserByUsername(username.replace(/^@/, ""));
    if (!other || other.id === user.id) {
        res.status(400).json({ error: "Unknown username" });
        return;
    }
    if (user.friendIds.includes(other.id)) {
        res.status(400).json({ error: "Already friends" });
        return;
    }
    await addFriend(user, other);
    res.status(201).json({ message: "Friend added", username: other.username });
});

export default router;
