import express from "express";
import { verifyAuthToken } from "../middleware/verifyAuthToken";
import { getFriends, searchUsers, getUserByUsername, addFriend } from "../database";

const router = express.Router();

router.get("/friends", verifyAuthToken, async (req, res) => {
    const friends = await getFriends(res.locals.user);
    res.json(friends);
});

// People search — NPCs generated by the world layer show up here too, so there
// are always singers to find and add.
router.get("/users", verifyAuthToken, async (req, res) => {
    const query = typeof req.query.q === "string" ? req.query.q : "";
    if (query === "") {
        res.json([]);
        return;
    }
    const users = await searchUsers(query, res.locals.user);
    res.json(users);
});

router.post("/friends", verifyAuthToken, async (req, res) => {
    const user = res.locals.user;
    const username: string = req.body.username;
    if (!username) {
        res.status(400).json({ error: "username is required" });
        return;
    }
    const other = await getUserByUsername(username.replace(/^@/, ""));
    if (!other || other.id === user.id) {
        res.status(400).json({ error: "Unknown username" });
        return;
    }
    if (user.friendIds.includes(other.id)) {
        res.status(400).json({ error: "Already friends" });
        return;
    }
    await addFriend(user, other);
    res.status(201).json({ message: "Friend added", username: other.username });
});

export default router;
