// `storybook.requires` is generated by the `withStorybook` Metro plugin
// (see metro.config.js) from this directory's `main.ts` stories glob —
// don't hand-edit it, and don't commit it; it's gitignored.
import { view } from "./storybook.requires";

const StorybookUI = view.getStorybookUI({});

export default StorybookUI;
